server:
  port: 9092

spring:
  application:
    name: domain-111
  datasource:
      name: test
      url: jdbc:mysql://144.34.225.227:3306/domain?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: 940519
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
  redis:
    database: 7
    host: 54.169.202.234
    port: 6379
    password:
  cache:
    type: redis
eureka:
  client:
    service-url:
      defaultZone: http://54.169.202.234:8761/eureka
  instance:
    prefer-ip-address: true

##禁止spring security默认的basic认证
security:
  basic:
    enabled: false
  oauth2:
    resource:
      id: domain-111
      user-info-uri: http://localhost:9090/auth/user
      prefer-token-info: false
## 开启断路由
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
#feign:
#  hystrix:
#    command:
#        default:
#          execution:
#            isolation:
#              thread:
#                timeoutInMilliseconds: 10000
#禁止spring security默认的basic认证
#security:
#  basic:
#    enabled: false

#security:
#  oauth2:
#    resource:
#      id: app-auth
#      user-info-uri: http://localhost:8080/auth/user
#      prefer-token-info: false

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.mydao.mab.domain
  #typeEnumsPackage: com.baomidou.springboot.entity.enums
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 1
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置
    #key-generator: com.baomidou.springboot.xxx
    #逻辑删除配置
    logic-delete-value: 0
    logic-not-delete-value: 1
    #自定义填充策略接口实现
    #meta-object-handler: com.baomidou.springboot.xxx
    #自定义SQL注入器
    #sql-injector: com.baomidou.springboot.xxx
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

